// Shared rendering for private saves and server-filtered friend snapshots.
export function gardenMetrics(row){
 if(!row)return {};
 const p=row.payload||{}, r=p.wildlife?.records||{}, n=v=>Number.isFinite(Number(v))?Number(v):0;
 const m={'Garden day':p.summary?.day??Math.floor((n(p.elapsed)+600)/2400)+1,'Coins':n(p.coins),'XP':n(p.experience?.total),'Level':1+Math.floor(n(p.experience?.total)/100),'Animals present':p.summary?.animals??null,'Species that visited':Object.keys(r).length,'Species made resident':Object.values(r).filter(x=>n(x.resident_day)>0).length,'Recorded gardening actions':p.gardening_actions??(p.experience?.worked?Object.keys(p.experience.worked).length:null),'Crops growing':p.crops_growing??p.crops?.length??null,'Crops harvested':p.harvested??null,'Items purchased':p.purchases instanceof Array?p.purchases.length:p.purchases??null,'Watered tiles':(Array.isArray(p.watered)?p.watered.filter(tile=>Array.isArray(tile)&&n(tile[2])>0).length:p.watered_tiles??null),'Births recorded':p.births??p.wildlife?.life_events?.filter(x=>x.kind==='birth').length??null,'Deaths recorded':p.deaths??p.wildlife?.life_events?.filter(x=>x.kind==='death').length??null,'Active garden minutes':Math.round(n(p.elapsed)/60),'Garden area (m²)':576,'Weather':['Fair','Cloudy','Light rain','Rain','Heavy rain','Thunderstorm','Clearing'][p.weather]??null,'Ground wetness':p.wetness==null?null:`${Math.round(n(p.wetness)*100)}%`};
 const cells=Array.isArray(p.terrain)?p.terrain:[];
 ['Dirt','Hard dirt','Grass','Long grass','Water','Deep water','Path','Stone'].forEach((name,i)=>{const count=cells.filter(x=>x===i).length;m[`${name} coverage`]=cells.length?`${(count/cells.length*100).toFixed(1)}%`:null;m[`${name} tiles`]=cells.length?count:null;m[`${name} area (m²)`]=cells.length?(count/cells.length*576).toFixed(1):null;});
 for(const [species,record] of Object.entries(r)){m[`${species}: first visit`]=record.visit_day?`Day ${record.visit_day}`:'Not yet';m[`${species}: resident since`]=record.resident_day?`Day ${record.resident_day}`:'Not yet';}
 return m;
}
